const os = require ("os")
console.log(os.arch())
// const freememory=os.freemem()
// console.log(`${freememory/1024/1024/1024}`)
// const totalmemory =os.totalmem()
// console.log(`${totalmemory/1024/1024/1024}`)
// console.log(os.platform())
// console.log(os.machine())
// console.log(os.version())
console.log(num)
var num =1